---
- name: Add Prometheus NGinx exporter YUM repositories
  yum_repository:
    name: '{{ ngx_exporter_repo_name }}'
    description: '{{ ngx_exporter_repo_name }} YUM repository'
    file: '{{ ngx_exporter_repo_name }}'
    baseurl: '{{ ngx_exporter_repo_url }}'
    gpgcheck: no

- name: Install the Prometheus NGinx exporter packages
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - '{{ ngx_exporter_software }}'

- name: Configures the time to sleep before restarting a NGinx exporter service
  lineinfile:
    state: present
    dest: '/lib/systemd/system/nginx_exporter.service'
    insertafter: '\[Service\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^RestartSec', line: 'RestartSec=10s' }

- name: Prometheus NGinx exporter configure file transfer
  template:
    src: 'nginx_exporter.default.j2'
    dest: '/etc/default/nginx_exporter'
    owner: 'root'
    group: 'root'
    mode: 0644
  register: conf_update

- name: Prometheus NGinx exporter service is enabled
  systemd:
    name: 'nginx_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: yes
  when:
    - conf_update|changed

- name: Register exporter service with an http health check
  uri:
    url: 'http://{{ item }}:{{ consul_http_port }}/v1/agent/service/register'
    method: 'PUT'
    headers:
      X-Consul-Token: "{{ consul_exporter_token }}"
    body: '{"ID":"{{ inventory_hostname | upper }}_nginx_exporter","name":"nginx_exporter","address":"{{ ansible_default_ipv4.address }}","port":{{ ngx_port_exporter }},"meta":{"instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[0] | upper }}","environment":"{{ environments | upper }}"},"checks":[{"http":"http://{{ ansible_default_ipv4.address }}:{{ ngx_port_exporter }}/metrics","interval":"60s","tls_skip_verify":true,"method":"HEAD","timeout":"5s"}]}'
    body_format: 'json'
  environment:
    no_proxy: '{{ item }}'
  with_items: '{{ consul_clients }}'
  when: consul_is_register
