---
- name: Add Prometheus NGinx exporter YUM repositories
  yum_repository:
    name: '{{ ngx_exporter_repo_name }}'
    description: '{{ ngx_exporter_repo_name }} YUM repository'
    file: '{{ ngx_exporter_repo_name }}'
    baseurl: '{{ ngx_exporter_repo_url }}'
    gpgcheck: 'no'
    sslverify: 'no'
    timeout: '60'

- name: Install the Prometheus NGinx exporter packages
  yum:
    name: '{{ ngx_exporter_software }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2

- name: Configures the time to sleep before restarting a NGinx exporter service
  lineinfile:
    state: present
    dest: '/lib/systemd/system/nginx_exporter.service'
    insertafter: '\[Service\]'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^RestartSec', line: 'RestartSec=10s' }

- name: Prometheus NGinx exporter configure file transfer
  template:
    src: 'nginx_exporter.default.j2'
    dest: '/etc/default/nginx_exporter'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: conf_update

- name: Prometheus NGinx exporter service is enabled
  systemd:
    name: 'nginx_exporter.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: yes
  when:
    - conf_update is changed
