---
- name: Gathering service facts
  service_facts:
  register: services_state

- name: Allow NGinx service port
  firewalld:
    port: '{{ item }}/tcp'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  with_items:
    - '{{ ngx_port_api }}'
    - '{{ ngx_port_exporter }}'
    - '{{ ngx_port_http }}'
    - '{{ ngx_port_https }}'
  when:
    - ansible_distribution_major_version|int > 6
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'
