---
- name: Allow NGinx service port
  firewalld:
    port: '{{ item }}/tcp'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  with_items:
    - '{{ ngx_port_api }}'
    - '{{ ngx_port_exporter }}'
    - '{{ ngx_port_http }}'
    - '{{ ngx_port_https }}'
  when: ansible_distribution_major_version|int > 6
