---
- name: Include tasks for specific OS
  include: '{{ ansible_os_family }}.yml'

- name: Configure the NGinx firewall
  include: 'firewall.yml'

- name: Straight to getenforce selinux status
  include: 'selinux.yml'

- name: Configuration the NGinx
  include: 'configureation.yml'

- name: Include certificate tasks
  include: 'certificates.yml'
  loop: '{{ ngx_site }}'
  loop_control:
    loop_var: ngx_site_item
  when: ngx_site is defined

- name: Generate strong Diffie–Hellman key exchange
  include: 'dhparam.yml'
  when: ngx_dhparam | bool

- name: Reload the service
  shell: echo ''
  notify: 'Reloading the Nginx service'
  when: conf_update is changed or site_update is changed or effects_update is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Include prometheus exporter tasks
  include: 'exporter.yml'
  when: exporter_is_install | bool

- name: Registered with HashiCorp Consul
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool
