---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add NGinx YUM repositories
  yum_repository:
    name: '{{ item.name }}'
    description: '{{ item.name }} repo'
    file: '{{ ngx_repo_name }}'
    baseurl: '{{ item.url }}'
    gpgcheck: 'no'
    timeout: '60'
  loop: '{{ vars["ngx_" + ngx_version + "_repo"] }}'

- name: Install the NGinx dependent packages
  yum:
    name: '{{ ",".join(vars["ngx_dependent_packages_" + ansible_os_family]) }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5

- name: Install the NGinx packages
  yum:
    name: '{{ ",".join(vars["ngx_standard_packages_" + ansible_os_family]) }}'
    state: 'present'
    enablerepo: 'nginx-basearch'
    validate_certs: 'no'
    update_cache: 'yes'  
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5

- name: Install the NGinx extras packages
  yum:
    name: '{{ ",".join(vars["ngx_extras_packages_" + ansible_os_family]) }}'
    state: 'present'
    enablerepo: 'nginx-basearch,nginx-noarch'
    validate_certs: 'no'
    update_cache: 'yes'
    disable_gpg_check: 'yes'
  when: ngx_version == 'extras'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5