---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add NGinx YUM repositories
  yum_repository:
    name: '{{ ngx_repo_name }}'
    description: '{{ ngx_repo_name }} repo'
    file: '{{ ngx_repo_name }}'
    baseurl: '{{ ngx_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the NGinx dependent packages
  yum:
    name: '{{ ngx_dependent_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2

- name: Install the NGinx packages
  yum:
    name: '{{ ngx_packages }}'
    state: 'present'
    enablerepo: '{{ ngx_repo_name }}'
    validate_certs: 'no'
    update_cache: 'yes'  
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2
