---
- name: Add NGINX YUM repositories
  yum_repository:
    name: '{{ ngx_repo_name }}'
    description: '{{ ngx_repo_name }} repo'
    file: '{{ ngx_repo_name }}'
    baseurl: '{{ vars["ngx_" + ngx_version + "_repo_url"] }}'
    gpgcheck: no

- name: Install the NGINX packages
  yum:
    name: '{{ ",".join(vars["ngx_" + ngx_version + "_packages_" + ansible_os_family]) }}'
    state: present
