---
- name: "Get getenforce binary"
  stat:
    path: '/usr/sbin/getenforce'
  register: getenforce_bin
  become: yes

- name: "Collect getenforce output"
  command: getenforce
  register: sestatus
  when: 'getenforce_bin.stat.exists'
  changed_when: false
  become: yes

- name: "Set nginx_selinux to true if getenforce returns Enforcing or Permissive"
  set_fact:
    nginx_selinux: "{{ true }}"
  when: 'getenforce_bin.stat.exists and ("Enforcing" in sestatus.stdout or "Permissive" in sestatus.stdout)'

- name: "Allow NGinx to start (SELinux)"
  selinux_permissive:
    name: 'httpd_t'
    permissive: true
  become: yes
  async: 35
  poll: 0
  when:
    - nginx_selinux

- name: Allow NGinx to set rlimit
  seboolean:
    name: 'httpd_setrlimit'
    state: yes
    persistent: yes
  when:
    - nginx_selinux    