---
- name: Ensure Nginx service is enabled
  systemd:
    name: 'nginx.service'
    enabled: yes
    state: reloaded
    daemon_reload: yes
  listen: 'Reloading the Nginx service'
  when: ansible_distribution_major_version|int > 6
